# Generated by Django 4.0.1 on 2022-01-15 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(max_length=30)),
                ('item_category', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('root_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
