# Generated by Django 4.0.1 on 2022-01-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apistore_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='root_user',
            new_name='customer',
        ),
    ]
