# Generated by Django 4.0.1 on 2022-01-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apistore_app', '0002_rename_root_user_items_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['purchased_date']},
        ),
    ]
