# Generated by Django 4.0.1 on 2022-01-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apistore_app', '0004_alter_items_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['item_category']},
        ),
    ]
