# Generated by Django 4.0.1 on 2022-01-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistore_app', '0006_alter_items_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.CharField(choices=[(5, 'Medicine'), (5, 'Food'), (3, 'Music'), (18, 'Imported'), (0, 'Book')], max_length=10),
        ),
    ]
