# Generated by Django 4.0.1 on 2022-01-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistore_app', '0005_alter_items_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.CharField(choices=[('M', 'Medicine'), ('F', 'Food'), ('N', 'Music'), ('I', 'Imported')], max_length=10),
        ),
    ]
