# Generated by Django 4.0.1 on 2022-01-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apistore_app', '0007_alter_items_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Food', 'Food'), ('Music', 'Music'), ('Imported', 'Imported'), ('Book', 'Book')], max_length=10),
        ),
    ]
